#### Production Environment ####
spring:
  main:
    banner-mode: 'off'
logging:
  file: @project.artifactId@-@project.version@.log
  level: # one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    root: ERROR

    #---- simter ----#
    tech.simter.kv.starter: INFO

    #---- spring ----#
    #org.springframework: WARN
    #org.springframework.web: WARN
    org.springframework.jdbc: INFO

    #---- spring-boot ----#
    #org.springframework.boot: WARN
    org.springframework.boot.context.embedded: INFO
    org.springframework.boot.web.embedded.netty.NettyWebServer: INFO # server port

    #---- hibernate sql ----#
    org.hibernate.tool: ERROR
    org.hibernate.tool.hbm2ddl: DEBUG
    #org.hibernate.SQL: DEBUG                                  # DEBUG for log by logger
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE # TRACE for show sql param value, such as 'binding parameter [N] as [SQL-TYPE] - [VALUE]'

    #---- hibernate jpql ----#
    #org.hibernate.engine.query.spi.HQLQueryPlan: TRACE   # TRACE for show jpql
    #org.hibernate.engine.spi.QueryParameters: TRACE      # TRACE for show jpql query parameter
    #org.hibernate.type.descriptor.converter.AttributeConverterSqlTypeDescriptorAdapter: DEBUG # DEBUG for value convert, such as 'Converted value on binding : Enabled -> 2'
