spring.test.database.replace: none
spring:
  datasource:
    platform: @db.platform@
    url: @db.url@
    host: @db.host@
    port: @db.port@
    name: @db.name@  # for postgres
    username: @db.username@
    password: @db.password@
    continue-on-error: @db.continue-on-error@
    sql-script-encoding: UTF-8
    #concat-sql-script: true # default false, true - save concatenate sql content to file target/{db.platform}.sql
    initialization-mode: @db.init-mode@ # never|embedded|always
    # available when initialization-mode=embedded|always
    schema:
      # drop
      - classpath:tech/simter/kv/sql/@db.platform@/schema-drop.sql
      # create
      - classpath:tech/simter/kv/sql/@db.platform@/schema-create.sql
    data:
      - classpath:tech/simter/kv/sql/@db.platform@/data.sql
    driver-class-name: @db.driver-class@
  data:
    mongodb:
      # mongodb://<user>:<password>@<host>:<port>/<db-name>
      uri: @db.url@
  mongodb:
    embedded:
      version: @mongo-embedded.version@
      #storage.database-dir: target/mongodb
simter.embedded-database:
  disabled-datasource: @db.disabled-datasource@ # default false, true - not auto instance and register a datasource
  postgres:
    port: @db.port@
    # available 9.5.16-1, 9.6.12-1, 10.7-1, 11.2-1
    version: @postgres-embedded.version@
    # default http://get.enterprisedb.com/postgresql/, can set to file:///C://Users//simter//download/
    download-url: ~
  mysql:
    # available 5.7.13~19, 5.7.10, 5.6.31~36, 5.6.21~24, 5.5.50~52, 5.5.40
    version: @mysql-embedded.version@
    # default http://get.enterprisedb.com/postgresql/, can set to file:///C://Users//simter//download/
    download-url: ~
simter.mongodb.enabled-logging-event-listener: ${debug:false}
# TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
logging.level:
  #---- simter ----#
  tech.simter.r2dbc: WARN # WARN - Executing spring.datasource.schema|data scripts to database, INFO - show executed script, DEBUG - show R2dbcProperties
  tech.simter.embeddeddatabase: WARN # WARN - Starting embedded database: url=..., INFO - Load script

  #---- r2dbc ----#
  #io.r2dbc.h2.client.SessionClient: DEBUG # DEBUG to show h2 request and response
  #io.r2dbc.postgresql.client.ReactorNettyClient: DEBUG # DEBUG to show postgres request and response
  io.r2dbc.postgresql.client.ReactorNettyClient: OFF # OFF - not show error '由于管理员命令中断联接'
  org.springframework.data.r2dbc.function.DefaultDatabaseClient: DEBUG # DEBUG to show sql

  #---- spring ----#
  org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory: INFO # INFO - Starting embedded database: url='jdbc:h2:mem:...', username='sa'
  #org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG # DEBUG - show executing SQL script file and result

  #---- mongo ----#
  #org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG # DEBUG to show query

  #---- embedded mongodb ----#
  #org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo: INFO # INFO - show initial and connection

  #---- flapdoodle ----#
  #de.flapdoodle.process.runtime.ProcessControl: DEBUG # DEBUG - Detected pid: 3252

  #---- embed postgres ----#
  #ru.yandex.qatools.embed.postgresql.PostgresProcess: INFO # INFO - trying to stop postgresql

  #---- embed mysql ----#
  #com.wix.mysql.EmbeddedMysql: INFO # INFO - Preparing EmbeddedMysql version 'Version 5.7.19'...
